cart/urls.py
from django.urls import path

from .views import *

app_name = 'cart'

urlpatterns = [
    path('', cart_detail, name='cart_detail'),
    path('add/<int:product_id>', cart_add, name='cart_add'),
    path('remove/<product_id>', cart_remove, name='cart_remove'),
]

coupons/urls.py
from django.urls import path
from .views import *
app_name='coupons'

urlpatterns = [
    path('apply/', coupon_apply, name='apply'),

]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('coupons/', include('coupons.urls')),
    path('orders/', include('orders.urls')),
    path('cart/', include('cart.urls')),
    path('', include('shop.urls')),
]

orders/urls.py
from django.urls import path
from .views import *
app_name = 'orders'

urlpatterns = [
    path('create/', order_create, name='order_create'),

    # Todo : Admin 용 뷰
    path('admin/order/<int:order_id>/', admin_order_detail, name='admin_order_detail'),
    path('admin/order/<int:order_id>/pdf/', admin_order_pdf, name='admin_order_pdf'),
    # Todo : 결제용 뷰
    path('create_ajax/', OrderCreateAjaxView.as_view(),name='order_create_ajax'),
    path('checkout/', OrderCheckoutAjaxView.as_view(),name='order_checkout'),
    path('validation/', OrderImpAjaxView.as_view(),name='order_validation'),
    path('complete/', order_complete,name='order_complete'),
]

shop/urls.py
from django.urls import path
from .views import *
app_name = 'shop'

urlpatterns = [
    path('', product_list, name='product_list'),
    path('<str:category_slug>/', product_list, name='product_list_by_category'),
    path('<int:id>/<product_slug>/', product_detail, name='product_detail'),
]

cart/models.py
from django.db import models

# Create your models here.

cart/forms.py
from django import forms

PRODUCT_QUANTITIES = [(i,str(i)) for i in range(1,21)]

class CartAddProductForm(forms.Form):
    quantity = forms.TypedChoiceField(choices=PRODUCT_QUANTITIES, coerce=int)
    update = forms.BooleanField(required=False, initial=False, widget=forms.HiddenInput)

cart/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_POST
from shop.models import Product
from .forms import *
from .cart import Cart

# Create your views here.
@require_POST
def cart_add(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)

    form = CartAddProductForm(request.POST)
    if form.is_valid():
        cd = form.cleaned_data
        cart.add(product=product, quantity=cd['quantity'], update_quantity=cd['update'])

    return redirect('cart:cart_detail')

def cart_remove(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    cart.remove(product)
    return redirect('cart:cart_detail')

from coupons.forms import CouponApplyForm
def cart_detail(request):
    cart = Cart(request)
    coupon_form = CouponApplyForm()
    test = request.session.get('coupon_id')
    for item in cart:
        item['update_quantity_form'] = CartAddProductForm(initial={'quantity':item['quantity'], 'update':True})
    return render(request, 'cart/detail.html', {'cart':cart, 'coupon_form':coupon_form,'test':test})

cart/templates/cart/detail.html
{% extends "base.html" %}
{% load static %}

{% block title %}
    Your shopping cart
{% endblock %}

{% block content %}
    <div class="alert alert-info" role="alert">
      Cart : Test {{test}}
    </div>
    <table class="table table-striped">
        <thead>
            <tr>
                <th scope="col">Image</th>
                <th scope="col">Product</th>
                <th scope="col">Quantity</th>
                <th scope="col">Remove</th>
                <th scope="col">Unit price</th>
                <th scope="col">Price</th>
            </tr>
        </thead>
        <tbody>
        {% for item in cart %}
            {% with product=item.product %}
            <tr>
                <th scope="row">
                    <a href="{{ product.get_absolute_url }}">
                        <img src="{{ product.image.url }}">
                    </a>
                </th>
                <td>{{ product.name }}</td>
                <td>
                    <form action="{% url "cart:cart_add" product.id %}" method="post">
                        {{ item.update_quantity_form.quantity }}
                        {{ item.update_quantity_form.update }}
                        <input type="submit" class="btn btn-primary" value="Update">
                        {% csrf_token %}
                    </form>
                </td>
                <td><a href="{% url "cart:cart_remove" product.id %}">Remove</a></td>
                <td class="num">${{ item.price }}</td>
                <td class="num">${{ item.total_price }}</td>
            </tr>
            {% endwith %}
        {% endfor %}

        {% if cart.coupon %}
            <tr class="subtotal">
                <td>Subtotal</td>
                <td colspan="4"></td>
                <td >${{ cart.get_total_price }}</td>
            </tr>
            <tr>
                    <td>"{{ cart.coupon.code }}" coupon ({{ cart.coupon.discount }}% off)</td>
                <td colspan="4"></td>
                <td >- ${{ cart.get_discount|floatformat:"2" }}</td>
            </tr>
        {% endif %}
        <tr class="total">
            <td>Total</td>
            <td colspan="4"></td>
            <td class="num">${{ cart.get_total_price_after_discount|floatformat:"2" }}</td>
        </tr>
        </tbody>
    </table>
    <p>
        Apply a coupon:
    </p>
    <form action='{% url "coupons:apply" %}' method="post">
        {{ coupon_form }}
        <input type="submit" value="Apply">
        {% csrf_token %}
    </form>

    <p class="text-right">
        <a href='{% url "shop:product_list" %}' class="btn btn-secondary">Continue shopping</a>
        <a href='{% url "orders:order_create" %}' class="btn btn-primary">Checkout</a>
    </p>
{% endblock %}